DROP TABLE books CASCADE;

CREATE TABLE books (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    year INTEGER,
    barcode_id INTEGER UNIQUE NOT NULL
);