CREATE TABLE borrows(
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE RESTRICT UNIQUE NOT NULL,
    username VARCHAR(30) NOT NULL,
    inventory_id INTEGER REFERENCES inventory(id) ON DELETE RESTRICT UNIQUE NOT NULL,
    current_state INTEGER NOT NULL,
    date_added DATE NOT NULL DEFAULT CURRENT_DATE
);